title: Francesco Denti # your name (or website title) here
logo: "/images/fra_blue.png" # your photo (or logo) here
description:  > # your text below (remove <br> elements if you don't need line breaks)
  
   A rookie with github pages
  

#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
theme: jekyll-theme-minimal
