---
title: "&nbsp;"
output: 
  md_document:
    variant: markdown_github
---
  
  <div style="text-align: right"> <p>&quot;<em>The writer Umberto Eco belongs to that small class of scholars who are encyclopedic, insightful, and nondull.<br>He is the owner of a large personal library (containing thirty thousand books), and separates visitors into two categories: those who react with “Wow! Signore, professore dottore Eco, what a library you have ! How many of these books have you read?” and the others - a very small minority - who get the point that a private library is not an ego-boosting appendage but a research tool.<br> Read books are far less valuable than unread ones.</em>&quot; <br> The Black Swan - N. N. Taleb</p>
  </div>
  
  
  
### About me
  
---
  
I am a Postdoctoral Scholar at the department of [Statistics of Univerisity of California - Irvine](https://www.stat.uci.edu/), working under the supervision of Professor [Babak Shahbaba](https://www.ics.uci.edu/~babaks/).  
I am interested in Bayesian statistics, Bayesian nonparametrics, model-based clustering, shrinkage priors, latent factor representation and more.  

* [Github Profile](https://github.com/Fradenti)

* [Google Scholar Profile](https://scholar.google.com/citations?user=DLiw19MAAAAJ&hl=en)


### Academia

---

* [Research](/Rmarkdowns/Research)

* [Presentations](/Rmarkdowns/ConferencesAndTalks)

* [Teaching](/Teaching)



### Misc

---

* [My second family (in italian)](http://www.compagniameteor.it/)

### Contacts

---

* **Email**: fdenti@uci.edu

